# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160320_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Champs',
        ),
        migrations.RenameField(
            model_name='champs',
            old_name='Titre',
            new_name='champs',
        ),
    ]
